### PR TITLE
add release script

### PR DESCRIPTION
**Pull request by taooceros**
https://github.com/Flow-Launcher/Flow.Launcher/issues/564

https://github.com/Flow-Launcher/Flow.Launcher/pull/563

### CODE REVIEW

**Review by jjw24 — APPROVED** [review]

**Comment by JohnTheGr8** [comment]
You guys didn't test this, did you? 😛 The paths are wrong... (I'm on it)

**Comment by taooceros** [comment]
I test it locally with another plugin and replace the name with myFlowPlugin 😂

**Comment by JohnTheGr8** [comment]
well, there's a bunch of problems actually:

1. the Output folder doesn't exist
2. the msbuild options are passed incorrectly to `dotnet publish`
3. the project is not passed to `dotnet publish` (which is necessary because it's in another folder)

Anyway, I'll fix this and bump the plugin dep to 2.0.0 for a new release.

**Comment by JohnTheGr8** [comment]
Using `Compress-Archive -LiteralPath` like that will put the plugin output inside a folder in the zip, do we know if Flow loads the plugin without problems in that case?

**Comment by jjw24** [comment]
Flow can load two directory levels, eg. /yourplugin/ or /yourplugin_parentfolder/yourplugin/

**Comment by JohnTheGr8** [comment]
Okay, I have updated plugin dependency to `2.0.0`, the project TFM to `net5.0-windows`, and fixed the release script. Am I missing anything wrt updating the plugin to be compatible with flow 1.8 ? Please let me know.

If not, the template is ready to go, and I'll publish it as v2.0.0

**Comment by jjw24** [comment]
lgtm

**Comment by taooceros** [comment]
Actually, I add the msbuild argument to dotnet publish because I would like to remove the pdb file in published folder, but anyway, that wasn't a bit deal.

**Comment by JohnTheGr8** [comment]
> 
> 
> Actually, I add the msbuild argument to dotnet publish because I would like to remove the pdb file in published folder, but anyway, that wasn't a bit deal.

That's what it does now, I just did it from the csproj file with the `DebugSymbols`/`DebugType` properties. FYI you used `/p:DebugType=None /p:DebugSymbols=false` with dotnet publish but it should've been `-p:DebugType=None -p:DebugSymbols=false`

**Pull request merged**
